# ####################################################################

#  Created by Genus(TM) Synthesis Solution 21.17-s066_1 on Sat Dec 13 13:51:49 EST 2025

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design alu_32bit

create_clock -name "clk" -period 1000.0 -waveform {0.0 500.0} 
set_load -pin_load 4.0 [get_ports {f_o[31]}]
set_load -pin_load 4.0 [get_ports {f_o[30]}]
set_load -pin_load 4.0 [get_ports {f_o[29]}]
set_load -pin_load 4.0 [get_ports {f_o[28]}]
set_load -pin_load 4.0 [get_ports {f_o[27]}]
set_load -pin_load 4.0 [get_ports {f_o[26]}]
set_load -pin_load 4.0 [get_ports {f_o[25]}]
set_load -pin_load 4.0 [get_ports {f_o[24]}]
set_load -pin_load 4.0 [get_ports {f_o[23]}]
set_load -pin_load 4.0 [get_ports {f_o[22]}]
set_load -pin_load 4.0 [get_ports {f_o[21]}]
set_load -pin_load 4.0 [get_ports {f_o[20]}]
set_load -pin_load 4.0 [get_ports {f_o[19]}]
set_load -pin_load 4.0 [get_ports {f_o[18]}]
set_load -pin_load 4.0 [get_ports {f_o[17]}]
set_load -pin_load 4.0 [get_ports {f_o[16]}]
set_load -pin_load 4.0 [get_ports {f_o[15]}]
set_load -pin_load 4.0 [get_ports {f_o[14]}]
set_load -pin_load 4.0 [get_ports {f_o[13]}]
set_load -pin_load 4.0 [get_ports {f_o[12]}]
set_load -pin_load 4.0 [get_ports {f_o[11]}]
set_load -pin_load 4.0 [get_ports {f_o[10]}]
set_load -pin_load 4.0 [get_ports {f_o[9]}]
set_load -pin_load 4.0 [get_ports {f_o[8]}]
set_load -pin_load 4.0 [get_ports {f_o[7]}]
set_load -pin_load 4.0 [get_ports {f_o[6]}]
set_load -pin_load 4.0 [get_ports {f_o[5]}]
set_load -pin_load 4.0 [get_ports {f_o[4]}]
set_load -pin_load 4.0 [get_ports {f_o[3]}]
set_load -pin_load 4.0 [get_ports {f_o[2]}]
set_load -pin_load 4.0 [get_ports {f_o[1]}]
set_load -pin_load 4.0 [get_ports {f_o[0]}]
set_load -pin_load 4.0 [get_ports cout_o]
set_clock_gating_check -setup 0.0 
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {sel_i[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {sel_i[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {sel_i[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {sel_i[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports cin_i]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[9]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[10]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[11]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[12]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[13]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[14]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[15]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[16]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[17]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[18]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[19]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[20]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[21]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[22]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[23]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[24]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[25]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[26]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[27]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[28]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[29]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[30]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {b_i[31]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[9]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[10]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[11]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[12]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[13]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[14]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[15]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[16]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[17]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[18]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[19]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[20]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[21]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[22]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[23]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[24]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[25]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[26]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[27]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[28]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[29]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[30]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.01 [get_ports {a_i[31]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports cout_o]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[4]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[5]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[6]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[7]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[8]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[9]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[10]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[11]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[12]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[13]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[14]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[15]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[16]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[17]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[18]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[19]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[20]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[21]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[22]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[23]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[24]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[25]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[26]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[27]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[28]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[29]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[30]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.03 [get_ports {f_o[31]}]
set_max_fanout 5.000 [get_ports {a_i[31]}]
set_max_fanout 5.000 [get_ports {a_i[30]}]
set_max_fanout 5.000 [get_ports {a_i[29]}]
set_max_fanout 5.000 [get_ports {a_i[28]}]
set_max_fanout 5.000 [get_ports {a_i[27]}]
set_max_fanout 5.000 [get_ports {a_i[26]}]
set_max_fanout 5.000 [get_ports {a_i[25]}]
set_max_fanout 5.000 [get_ports {a_i[24]}]
set_max_fanout 5.000 [get_ports {a_i[23]}]
set_max_fanout 5.000 [get_ports {a_i[22]}]
set_max_fanout 5.000 [get_ports {a_i[21]}]
set_max_fanout 5.000 [get_ports {a_i[20]}]
set_max_fanout 5.000 [get_ports {a_i[19]}]
set_max_fanout 5.000 [get_ports {a_i[18]}]
set_max_fanout 5.000 [get_ports {a_i[17]}]
set_max_fanout 5.000 [get_ports {a_i[16]}]
set_max_fanout 5.000 [get_ports {a_i[15]}]
set_max_fanout 5.000 [get_ports {a_i[14]}]
set_max_fanout 5.000 [get_ports {a_i[13]}]
set_max_fanout 5.000 [get_ports {a_i[12]}]
set_max_fanout 5.000 [get_ports {a_i[11]}]
set_max_fanout 5.000 [get_ports {a_i[10]}]
set_max_fanout 5.000 [get_ports {a_i[9]}]
set_max_fanout 5.000 [get_ports {a_i[8]}]
set_max_fanout 5.000 [get_ports {a_i[7]}]
set_max_fanout 5.000 [get_ports {a_i[6]}]
set_max_fanout 5.000 [get_ports {a_i[5]}]
set_max_fanout 5.000 [get_ports {a_i[4]}]
set_max_fanout 5.000 [get_ports {a_i[3]}]
set_max_fanout 5.000 [get_ports {a_i[2]}]
set_max_fanout 5.000 [get_ports {a_i[1]}]
set_max_fanout 5.000 [get_ports {a_i[0]}]
set_max_fanout 5.000 [get_ports {b_i[31]}]
set_max_fanout 5.000 [get_ports {b_i[30]}]
set_max_fanout 5.000 [get_ports {b_i[29]}]
set_max_fanout 5.000 [get_ports {b_i[28]}]
set_max_fanout 5.000 [get_ports {b_i[27]}]
set_max_fanout 5.000 [get_ports {b_i[26]}]
set_max_fanout 5.000 [get_ports {b_i[25]}]
set_max_fanout 5.000 [get_ports {b_i[24]}]
set_max_fanout 5.000 [get_ports {b_i[23]}]
set_max_fanout 5.000 [get_ports {b_i[22]}]
set_max_fanout 5.000 [get_ports {b_i[21]}]
set_max_fanout 5.000 [get_ports {b_i[20]}]
set_max_fanout 5.000 [get_ports {b_i[19]}]
set_max_fanout 5.000 [get_ports {b_i[18]}]
set_max_fanout 5.000 [get_ports {b_i[17]}]
set_max_fanout 5.000 [get_ports {b_i[16]}]
set_max_fanout 5.000 [get_ports {b_i[15]}]
set_max_fanout 5.000 [get_ports {b_i[14]}]
set_max_fanout 5.000 [get_ports {b_i[13]}]
set_max_fanout 5.000 [get_ports {b_i[12]}]
set_max_fanout 5.000 [get_ports {b_i[11]}]
set_max_fanout 5.000 [get_ports {b_i[10]}]
set_max_fanout 5.000 [get_ports {b_i[9]}]
set_max_fanout 5.000 [get_ports {b_i[8]}]
set_max_fanout 5.000 [get_ports {b_i[7]}]
set_max_fanout 5.000 [get_ports {b_i[6]}]
set_max_fanout 5.000 [get_ports {b_i[5]}]
set_max_fanout 5.000 [get_ports {b_i[4]}]
set_max_fanout 5.000 [get_ports {b_i[3]}]
set_max_fanout 5.000 [get_ports {b_i[2]}]
set_max_fanout 5.000 [get_ports {b_i[1]}]
set_max_fanout 5.000 [get_ports {b_i[0]}]
set_max_fanout 5.000 [get_ports cin_i]
set_max_fanout 5.000 [get_ports {sel_i[3]}]
set_max_fanout 5.000 [get_ports {sel_i[2]}]
set_max_fanout 5.000 [get_ports {sel_i[1]}]
set_max_fanout 5.000 [get_ports {sel_i[0]}]
set_drive 2.0 [get_ports {a_i[31]}]
set_drive 2.0 [get_ports {a_i[30]}]
set_drive 2.0 [get_ports {a_i[29]}]
set_drive 2.0 [get_ports {a_i[28]}]
set_drive 2.0 [get_ports {a_i[27]}]
set_drive 2.0 [get_ports {a_i[26]}]
set_drive 2.0 [get_ports {a_i[25]}]
set_drive 2.0 [get_ports {a_i[24]}]
set_drive 2.0 [get_ports {a_i[23]}]
set_drive 2.0 [get_ports {a_i[22]}]
set_drive 2.0 [get_ports {a_i[21]}]
set_drive 2.0 [get_ports {a_i[20]}]
set_drive 2.0 [get_ports {a_i[19]}]
set_drive 2.0 [get_ports {a_i[18]}]
set_drive 2.0 [get_ports {a_i[17]}]
set_drive 2.0 [get_ports {a_i[16]}]
set_drive 2.0 [get_ports {a_i[15]}]
set_drive 2.0 [get_ports {a_i[14]}]
set_drive 2.0 [get_ports {a_i[13]}]
set_drive 2.0 [get_ports {a_i[12]}]
set_drive 2.0 [get_ports {a_i[11]}]
set_drive 2.0 [get_ports {a_i[10]}]
set_drive 2.0 [get_ports {a_i[9]}]
set_drive 2.0 [get_ports {a_i[8]}]
set_drive 2.0 [get_ports {a_i[7]}]
set_drive 2.0 [get_ports {a_i[6]}]
set_drive 2.0 [get_ports {a_i[5]}]
set_drive 2.0 [get_ports {a_i[4]}]
set_drive 2.0 [get_ports {a_i[3]}]
set_drive 2.0 [get_ports {a_i[2]}]
set_drive 2.0 [get_ports {a_i[1]}]
set_drive 2.0 [get_ports {a_i[0]}]
set_drive 2.0 [get_ports {b_i[31]}]
set_drive 2.0 [get_ports {b_i[30]}]
set_drive 2.0 [get_ports {b_i[29]}]
set_drive 2.0 [get_ports {b_i[28]}]
set_drive 2.0 [get_ports {b_i[27]}]
set_drive 2.0 [get_ports {b_i[26]}]
set_drive 2.0 [get_ports {b_i[25]}]
set_drive 2.0 [get_ports {b_i[24]}]
set_drive 2.0 [get_ports {b_i[23]}]
set_drive 2.0 [get_ports {b_i[22]}]
set_drive 2.0 [get_ports {b_i[21]}]
set_drive 2.0 [get_ports {b_i[20]}]
set_drive 2.0 [get_ports {b_i[19]}]
set_drive 2.0 [get_ports {b_i[18]}]
set_drive 2.0 [get_ports {b_i[17]}]
set_drive 2.0 [get_ports {b_i[16]}]
set_drive 2.0 [get_ports {b_i[15]}]
set_drive 2.0 [get_ports {b_i[14]}]
set_drive 2.0 [get_ports {b_i[13]}]
set_drive 2.0 [get_ports {b_i[12]}]
set_drive 2.0 [get_ports {b_i[11]}]
set_drive 2.0 [get_ports {b_i[10]}]
set_drive 2.0 [get_ports {b_i[9]}]
set_drive 2.0 [get_ports {b_i[8]}]
set_drive 2.0 [get_ports {b_i[7]}]
set_drive 2.0 [get_ports {b_i[6]}]
set_drive 2.0 [get_ports {b_i[5]}]
set_drive 2.0 [get_ports {b_i[4]}]
set_drive 2.0 [get_ports {b_i[3]}]
set_drive 2.0 [get_ports {b_i[2]}]
set_drive 2.0 [get_ports {b_i[1]}]
set_drive 2.0 [get_ports {b_i[0]}]
set_drive 2.0 [get_ports cin_i]
set_drive 2.0 [get_ports {sel_i[3]}]
set_drive 2.0 [get_ports {sel_i[2]}]
set_drive 2.0 [get_ports {sel_i[1]}]
set_drive 2.0 [get_ports {sel_i[0]}]
set_wire_load_mode "enclosed"
