
// Generated by Cadence Genus(TM) Synthesis Solution 21.17-s066_1
// Generated on: Dec 12 2025 02:51:35 EST (Dec 12 2025 07:51:35 UTC)

// Verification Directory fv/alu_1bit 

module full_adder(a_i, b_i, cin_i, sum_o, cout_o);
  input a_i, b_i, cin_i;
  output sum_o, cout_o;
  wire a_i, b_i, cin_i;
  wire sum_o, cout_o;
  wire n_23;
  CLKBUFX20 drc_bufs(.A (n_23), .Y (cout_o));
  ADDFHXL g87(.A (b_i), .B (a_i), .CI (cin_i), .CO (n_23), .S (sum_o));
endmodule

module mux4x1(a, b, c, d, sel, y);
  input a, b, c, d;
  input [1:0] sel;
  output y;
  wire a, b, c, d;
  wire [1:0] sel;
  wire y;
  wire n_0;
  XNOR2X1 g33__5526(.A (sel[0]), .B (n_0), .Y (y));
  NAND2BX1 g34__6783(.AN (sel[1]), .B (a), .Y (n_0));
endmodule

module arithmetic_circuit(a_i, b_i, cin_i, sel_i, d_o, cout_o);
  input a_i, b_i, cin_i;
  input [1:0] sel_i;
  output d_o, cout_o;
  wire a_i, b_i, cin_i;
  wire [1:0] sel_i;
  wire d_o, cout_o;
  wire UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z1,
       mux_b_o;
  full_adder u_full_adder(.a_i (a_i), .b_i (mux_b_o), .cin_i (cin_i),
       .sum_o (d_o), .cout_o (cout_o));
  mux4x1 u_mux4x1(.a (b_i), .b (UNCONNECTED_HIER_Z), .c
       (UNCONNECTED_HIER_Z0), .d (UNCONNECTED_HIER_Z1), .sel (sel_i),
       .y (mux_b_o));
endmodule

module alu_1bit(a_i, b_i, cin_i, sel_i, f_o, cout_o);
  input a_i, b_i, cin_i;
  input [3:0] sel_i;
  output f_o, cout_o;
  wire a_i, b_i, cin_i;
  wire [3:0] sel_i;
  wire f_o, cout_o;
  wire d_o, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  arithmetic_circuit u_arithmetic_circuit(.a_i (a_i), .b_i (b_i),
       .cin_i (cin_i), .sel_i (sel_i[1:0]), .d_o (d_o), .cout_o
       (cout_o));
  MX2X1 g253__3680(.A (d_o), .B (n_5), .S0 (sel_i[2]), .Y (n_6));
  OAI21X1 g254__1617(.A0 (n_2), .A1 (n_3), .B0 (n_4), .Y (n_5));
  AOI33XL g255__2802(.A0 (sel_i[1]), .A1 (a_i), .A2 (n_2), .B0
       (sel_i[0]), .B1 (b_i), .B2 (n_1), .Y (n_4));
  MXI2XL g256__1705(.A (a_i), .B (n_1), .S0 (sel_i[1]), .Y (n_3));
  NOR2X1 g257__5122(.A (sel_i[0]), .B (b_i), .Y (n_2));
  INVX1 g259(.A (a_i), .Y (n_1));
  CLKBUFX20 drc_bufs(.A (n_0), .Y (f_o));
  NOR2BX1 g2__8246(.AN (n_6), .B (sel_i[3]), .Y (n_0));
endmodule

